export const Theme = {
  colors: {
    surface: '#1b202d',
    surfaceDim: '#161922',
    surfaceBright: '#262d3d',
    surfaceContainerLowest: '#0a0d14',
    surfaceContainerLow: '#161922',
    surfaceContainer: '#1b202d',
    surfaceContainerHigh: '#262d3d',
    surfaceContainerHighest: '#323a4d',
    onSurface: '#f7f9fc',
    onSurfaceVariant: '#9ca3af',
    inverseSurface: '#eff1f4',
    inverseOnSurface: '#191c1e',
    outline: '#4b5563',
    outlineVariant: '#374151',
    surfaceTint: '#9ca3af',
    primary: '#ffffff',
    onPrimary: '#000000',
    primaryContainer: '#3b82f6',
    onPrimaryContainer: '#eff6ff',
    inversePrimary: '#1d4ed8',
    secondary: '#f97316',
    onSecondary: '#ffffff',
    secondaryContainer: '#c2410c',
    onSecondaryContainer: '#fff7ed',
    tertiary: '#10b981',
    onTertiary: '#ffffff',
    tertiaryContainer: '#047857',
    onTertiaryContainer: '#ecfdf5',
    error: '#ef4444',
    onError: '#ffffff',
    errorContainer: '#991b1b',
    onErrorContainer: '#fef2f2',
    background: '#0a0d14',
    onBackground: '#f7f9fc',
    surfaceVariant: '#262d3d',
    tertiaryFixedDim: '#30e375',
  },
  typography: {
    displayLg: { fontFamily: 'Inter_700Bold', fontSize: 48, lineHeight: 56, letterSpacing: -0.96 },
    headlineLg: { fontFamily: 'Inter_600SemiBold', fontSize: 32, lineHeight: 40, letterSpacing: -0.32 },
    headlineLgMobile: { fontFamily: 'Inter_600SemiBold', fontSize: 24, lineHeight: 32 },
    headlineMd: { fontFamily: 'Inter_600SemiBold', fontSize: 20, lineHeight: 28 },
    bodyLg: { fontFamily: 'Inter_400Regular', fontSize: 18, lineHeight: 28 },
    bodyMd: { fontFamily: 'Inter_400Regular', fontSize: 16, lineHeight: 24 },
    metricLg: { fontFamily: 'JetBrainsMono_600SemiBold', fontSize: 24, lineHeight: 32 },
    metricSm: { fontFamily: 'JetBrainsMono_500Medium', fontSize: 14, lineHeight: 20 },
    labelCaps: { fontFamily: 'Inter_700Bold', fontSize: 12, lineHeight: 16, letterSpacing: 0.6, textTransform: 'uppercase' as const },
  },
  spacing: {
    base: 4,
    xs: 8,
    sm: 16,
    md: 24,
    lg: 40,
    xl: 64,
    gutter: 16,
    marginMobile: 20,
    marginDesktop: 48,
  },
  radius: {
    sm: 2,
    DEFAULT: 4,
    md: 6,
    lg: 8,
    xl: 12,
    full: 9999,
  }
};
