export const Theme = {
  colors: {
    surface: '#f7f9fc',
    surfaceDim: '#d8dadd',
    surfaceBright: '#f7f9fc',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#f2f4f7',
    surfaceContainer: '#eceef1',
    surfaceContainerHigh: '#e6e8eb',
    surfaceContainerHighest: '#e0e3e6',
    onSurface: '#191c1e',
    onSurfaceVariant: '#44474a',
    inverseSurface: '#2d3133',
    inverseOnSurface: '#eff1f4',
    outline: '#75777a',
    outlineVariant: '#c5c6ca',
    surfaceTint: '#5d5e61',
    primary: '#000101',
    onPrimary: '#ffffff',
    primaryContainer: '#1a1c1e',
    onPrimaryContainer: '#838486',
    inversePrimary: '#c6c6c9',
    secondary: '#a33800',
    onSecondary: '#ffffff',
    secondaryContainer: '#cd4800',
    onSecondaryContainer: '#fffbff',
    tertiary: '#000200',
    onTertiary: '#ffffff',
    tertiaryContainer: '#00220b',
    onTertiaryContainer: '#009949',
    error: '#ba1a1a',
    onError: '#ffffff',
    errorContainer: '#ffdad6',
    onErrorContainer: '#93000a',
    background: '#f7f9fc',
    onBackground: '#191c1e',
    surfaceVariant: '#e0e3e6',
    tertiaryFixedDim: '#30e375', // added from home_dashboard html
  },
  typography: {
    displayLg: { fontFamily: 'Inter_700Bold', fontSize: 48, lineHeight: 56, letterSpacing: -0.96 },
    headlineLg: { fontFamily: 'Inter_600SemiBold', fontSize: 32, lineHeight: 40, letterSpacing: -0.32 },
    headlineLgMobile: { fontFamily: 'Inter_600SemiBold', fontSize: 24, lineHeight: 32 },
    headlineMd: { fontFamily: 'Inter_600SemiBold', fontSize: 20, lineHeight: 28 },
    bodyLg: { fontFamily: 'Inter_400Regular', fontSize: 18, lineHeight: 28 },
    bodyMd: { fontFamily: 'Inter_400Regular', fontSize: 16, lineHeight: 24 },
    metricLg: { fontFamily: 'JetBrainsMono_600SemiBold', fontSize: 24, lineHeight: 32 },
    metricSm: { fontFamily: 'JetBrainsMono_500Medium', fontSize: 14, lineHeight: 20 },
    labelCaps: { fontFamily: 'Inter_700Bold', fontSize: 12, lineHeight: 16, letterSpacing: 0.6, textTransform: 'uppercase' as const },
  },
  spacing: {
    base: 4,
    xs: 8,
    sm: 16,
    md: 24,
    lg: 40,
    xl: 64,
    gutter: 16,
    marginMobile: 20,
    marginDesktop: 48,
  },
  radius: {
    sm: 2,
    DEFAULT: 4,
    md: 6,
    lg: 8,
    xl: 12,
    full: 9999,
  }
};
